- name: service-one
  tags:
    - service
  watch:
    fs:
      path: cmd/service-one/
  env:
    - name: VAR_1
      value: VAL_1
    - name: VAR_2
      value: VAL_2
    - name: VAR_NO_VALUE
    - name: VAR_EMPTY
    - name: PATH
    - name: PWD
    - name: GOCACHE
    - name: HOME
      value:
  before: echo "do something at first run"
  run: go run cmd/service-one/main.go

- name: service-two
  tags:
    - service
  env:
    - name: VAR_3
      value: VAL_3
    - name: VAR_4
      value: VAL_4
    - name: VAR_NO_VALUE
    - name: VAR_EMPTY_QUOTE
      value: ""
  watch:
    fs:
      paths:
        - cmd/service-two/main.go
  run: go run cmd/service-two/main.go
